import type { Card, UnitCard } from '../types/cards';

const materialUnits: UnitCard[] = [
  {
    id: 'warm_welcome',
    name: 'Warm Welcome',
    type: 'unit',
    layer: 'material',
    cost: { material: 1, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 1,
    abilities: [],
    artworkUrl: 'warm_welcome.png',
  },
  {
    id: 'here_to_help',
    name: 'Here To Help',
    type: 'unit',
    layer: 'material',
    cost: { material: 1, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 1,
    abilities: [],
    artworkUrl: 'here_to_help.png',
  },
  {
    id: 'stair_people',
    name: 'Stair People',
    type: 'unit',
    layer: 'material',
    cost: { material: 1, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 1,
    abilities: [],
    artworkUrl: 'stair_people.png',
  },
  {
    id: 'who_am_i',
    name: 'Who Am I',
    type: 'unit',
    layer: 'material',
    cost: { material: 1, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 2,
    abilities: [],
    artworkUrl: 'who_am_i.png',
  },
  {
    id: 'ill_wait',
    name: "I'll Wait",
    type: 'unit',
    layer: 'material',
    cost: { material: 2, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 2,
    abilities: [],
    artworkUrl: 'ill_wait.png',
  },
  {
    id: 'third_door',
    name: 'Third Door',
    type: 'unit',
    layer: 'material',
    cost: { material: 2, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 3,
    abilities: [],
    artworkUrl: 'third_door.png',
  },
  {
    id: 'recurring_visitor',
    name: 'Recurring Visitor',
    type: 'unit',
    layer: 'material',
    cost: { material: 2, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 1,
    abilities: [],
    artworkUrl: 'recurring_visitor.png',
  },
  {
    id: 'keep_watching',
    name: 'Keep Watching',
    type: 'unit',
    layer: 'material',
    cost: { material: 2, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 3,
    abilities: [],
    artworkUrl: 'keep_watching.png',
  },
  {
    id: 'familiar_stranger',
    name: 'Familiar Stranger',
    type: 'unit',
    layer: 'material',
    cost: { material: 3, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 3,
    abilities: [],
    artworkUrl: 'familiar_stranger.png',
  },
  {
    id: 'basement',
    name: 'Basement',
    type: 'unit',
    layer: 'material',
    cost: { material: 3, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 4,
    defense: 2,
    abilities: [],
    artworkUrl: 'basement.png',
  },
  {
    id: 'it_wasnt_me',
    name: "It Wasn't Me",
    type: 'unit',
    layer: 'material',
    cost: { material: 3, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 4,
    abilities: [],
    artworkUrl: 'it_wasnt_me.png',
  },
  {
    id: 'skin_tight',
    name: 'Skin Tight',
    type: 'unit',
    layer: 'material',
    cost: { material: 3, mind: 0 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 4,
    abilities: [],
    artworkUrl: 'skin_tight.png',
  },
];

export const materialTestCards: Card[] = [...materialUnits];
