import type { Card, UnitCard } from '../types/cards';

const mindUnits: UnitCard[] = [
  {
    id: 'wrong_name',
    name: 'Wrong Name',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 1 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 0,
    abilities: [],
    artworkUrl: 'wrong_name.png',
  },
  {
    id: 'last_photo',
    name: 'Last Photo',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 1 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 1,
    abilities: [],
    artworkUrl: 'last_photo.png',
  },
  {
    id: 'sleep_walker',
    name: 'Sleep Walker',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 1 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 1,
    abilities: [],
    artworkUrl: 'sleep_walker.png',
  },
  {
    id: 'cold_hands',
    name: 'Cold Hands',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 1 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 2,
    abilities: [],
    artworkUrl: 'cold_hands.png',
  },
  {
    id: 'identity',
    name: 'Identity',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 2 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 1,
    abilities: [],
    artworkUrl: 'identity.png',
  },
  {
    id: 'never_born',
    name: 'Never Born',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 2 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 1,
    defense: 3,
    abilities: [],
    artworkUrl: 'never_born.png',
  },
  {
    id: 'almost_human',
    name: 'Almost Human',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 2 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 1,
    abilities: [],
    artworkUrl: 'almost_human.png',
  },
  {
    id: 'mother',
    name: 'Mother',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 2 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 1,
    abilities: [],
    artworkUrl: 'mother.png',
  },
  {
    id: 'always_awake',
    name: 'Always Awake',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 3 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 3,
    abilities: [],
    artworkUrl: 'always_awake.png',
  },
  {
    id: 'voice',
    name: 'Voice',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 3 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 4,
    defense: 2,
    abilities: [],
    artworkUrl: 'voice.png',
  },
  {
    id: 'family',
    name: 'Family',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 3 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 2,
    defense: 4,
    abilities: [],
    artworkUrl: 'family.png',
  },
  {
    id: 'remember_me',
    name: 'Remember Me',
    type: 'unit',
    layer: 'mind',
    cost: { material: 0, mind: 3 },
    rarity: 'common',
    set: 'core',
    releaseDate: Date.now(),
    attack: 3,
    defense: 4,
    abilities: [],
    artworkUrl: 'remember_me.png',
  },
];

export const mindTestCards: Card[] = [...mindUnits];
